### PR TITLE
Fix XeLL freeze on 'requesting dhcp' when plugged into ethernet

### PR DESCRIPTION
**Pull request by AidenIsik**
This bug is not present on the Free60Project branch of LibXenon. So, I basically just copied their lwip folder into here and now it doesn't freeze on requesting dhcp.

If there's a more sane way of fixing this you'd rather do, please feel free to disregard this pull request ;p

### CODE REVIEW

**Comment by AidenIsik** [comment]
tl;dr I made it use their lwip setup instead of this one, and it seems to work and not freeze

**Comment by AidenIsik** [comment]
Note that I managed to reproduce this bug on both a Trinity XDK via XeLLLaunch, and an RGH3 Falcon via the NAND XeLL

**Comment by Octal450** [comment]
I don't have such an issue any any of the consoles I did in the 1 year+ since releasing the build. I reverted some LWIP changes because they introduced other bugs - maybe that's been fixed.

I can't evaluate this properly until I am home in December, so unfortunately will have to wait until then to merge. I definitely will check it though.

Kind Regards,
Josh

**Comment by AidenIsik** [comment]
Thanks for taking the time to reply.

You mentioned that this works for others. I think it's likely, in this case, that my network configuration may be causing this issue. I have two routers attached together, one of which is meant to be acting as an access point/switch, but it seems I left the DHCP server enabled on both. 

I'll test it with the second server disabled tomorrow, and if it works I'll close this pull request myself, especially if there's a high chance of reintroducing bugs, as I don't want to cause a headache.

**Comment by Octal450** [comment]
Hi,
No no need.

They went through and fixed a lot in the last year I believe. It's possible the issues I had in 2021 are fixed.

I will re-evaluate in December when I am home.

Kind Regards,
Josh

**Comment by AidenIsik** [comment]
Hi, I recently got a new router and the issue has been resolved.

I'll leave this up in case you still want to consider it, but it was at least partially a configuration issue.

**Comment by Coolumin** [comment]
Not sure why his account is deleted, but it seems to still be a problem as seen in https://github.com/Octal450/J-Runner-with-Extras/issues/55

**Pull request closed without merging**
